add ironic tutorial
vietstacker/vietstacker.github.io pull request #35
Opened 2017-05-29 06:32 UTC by Tuanlase02874

Add Bare Metal Provision with Portgroup used Fujitsu Server Tutorial

2017-05-29 06:44 UTC, tovin07 commented on _posts/2017-05-29-HA of Bare metal.md
> +```
để code format là INI hoặc Config đi cho nó highlight

2017-05-29 06:45 UTC, tovin07 commented on _posts/2017-05-29-HA of Bare metal.md
> +>_$ git clone https://git.openstack.org/openstack-dev/devstack.git devstack_
để shell code nhá, tất các chỗ khác cũng thé luôn

2017-05-29 06:49 UTC, tovin07 commented on _posts/2017-05-29-HA of Bare metal.md
> +##1. Introduction ironic port groups support
thiếu dấu cách sau dấu # rồi

2017-05-29 06:50 UTC, tovin07 commented on _posts/2017-05-29-HA of Bare metal.md
> +![IronicAPI create node for Bare Metal Provisioning.](../pictures/ironic_create.png)
thay vì để hình, chú copy y nguyên output của lệnh này rồi để vào trong code section đi

2017-05-29 06:52 UTC, tovin07 commented on _posts/2017-05-29-HA of Bare metal.md
> +
Giãn dòng ít thôi nhé :smile:

2017-05-29 06:57 UTC, tovin07 requested changes
Bài viết rất chi tiết.

Tuy nhiên, còn nhiều điểm cần phải sửa trước khi publish. Anh liệt kê tạm ra đây mấy điểm, sửa dần dần:

1. Bỏ mấy file HTML đi, jekyll nó tự lo việc compile md cho chú.
2. Một đống magic string, magic number, đề nghị chú thích ý nghĩa, từ đâu mà có những cái đó.
3. Output của CLI thì nên copy raw rồi để vào trong thẻ code để dễ đọc, dễ copy, dễ quan sát và không bị phụ thuộc vào màu theme của blog nếu như thay đổi.
4. Sửa lại tất cả các chỗ trình bày lỗi liên quan đến MD, chú cứ thử bấm view file md trong pull request của chú sẽ thấy cái output nó trông dở như thế nào.

Ví dụ về độ dở sau khi render: https://github.com/Tuanlase02874/vietstacker.github.io/blob/c80d999af402f4e36e2393d7156af5823f5bd0a0/_posts/2017-05-29-HA%20of%20Bare%20metal.md

Đấy là comment của anh, chú sửa dần đi nhé, chắc chắn sẽ có nhiều comment nữa từ các Organizer khác.

Thân ái! :v

2017-05-29 07:52 UTC, congto commented
@Tuanlase02874 @tovin07 

Thay mặt BQT anh có lời khen các em về tinh thần chia sẻ của các em. Mọi góp ý về kỹ thuật các anh trong BQT sẽ tiếp tục giúp anh nhé.

Công TÔ

2017-05-29 15:00 UTC, tovin07 commented on _posts/2017-05-29-HA of Bare metal.md
> +The Bare Metal Service (ironic) [3] supports static configuration of **port groups** (PG) will allow user to increase performance or provide higher reliability of network connection. PG can be called
Đoạn này viết lại được không chú? Anh thấy nó rất "văn nói" và ngữ pháp còn không đúng.

2017-05-29 15:01 UTC, tovin07 commented on _posts/2017-05-29-HA of Bare metal.md
> +The requirement for tutorial include two computer:
câu này cũng có vấn đề này
```
The requirement for tutorial include two computer:
```

2017-05-30 01:05 UTC, hieulq requested changes
nit: tên file không có ký tự đặc biệt, khoảng trắng.
còn lại thì ok rồi.

2017-05-30 01:05 UTC, hieulq commented on _posts/2017-05-29-HA of Bare metal.md
> +This tutorial will show how to create bare metal computer (BM) with port groups support follow the network prototype here:
following

2017-05-30 01:08 UTC, hieulq requested changes
Ngoài ra, bổ sung phần sau vào đầu file (metadata cho jekyll):
---
layout: post
title: <thay tiêu đề của em>
date: <thay date của em>
type: post
published: true
status: publish
categories:
- Hướng dẫn cài đặt
- News
tags:
- ironic
- portgroup
- openstack
<thêm tag nào em muốn>
meta:
  _publicize_pending: '1'
author:
  login: <nick github>
  email: <email của em>
  display_name: <Tên em>
  first_name: '<tên>'
  last_name: '<họ>'
---
<nội dung chính>

2017-05-30 01:09 UTC, hieulq commented
@Tuanlase02874 xem ví dụ ở đây: https://raw.githubusercontent.com/vietstacker/vietstacker.github.io/master/_posts/2014-02-14-huong-dan-cai-dat-openstack-havana-theo-devstack.md

Có gì khó thì hỏi siêu nhân @congto  nhé ;)

2017-05-30 03:01 UTC, Tuanlase02874 commented on _posts/2017-05-29-HA of Bare metal.md
> +```
done

2017-05-30 03:09 UTC, Tuanlase02874 commented on _posts/2017-05-29-HA of Bare metal.md
> +>_$ git clone https://git.openstack.org/openstack-dev/devstack.git devstack_
done

2017-05-30 03:11 UTC, Tuanlase02874 commented on _posts/2017-05-29-HA of Bare metal.md
> +![IronicAPI create node for Bare Metal Provisioning.](../pictures/ironic_create.png)
Thanks, Next time, Will improving

2017-05-30 03:15 UTC, Tuanlase02874 commented on _posts/2017-05-29-HA of Bare metal.md
> +The Bare Metal Service (ironic) [3] supports static configuration of **port groups** (PG) will allow user to increase performance or provide higher reliability of network connection. PG can be called
Done,

2017-05-30 03:18 UTC, Tuanlase02874 commented on _posts/2017-05-29-HA of Bare metal.md
> +The requirement for tutorial include two computer:
thanks, I fix Requirements for bare Metal provisioning tutorial:

2017-05-30 03:18 UTC, Tuanlase02874 commented on _posts/2017-05-29-HA of Bare metal.md
> +This tutorial will show how to create bare metal computer (BM) with port groups support follow the network prototype here:
Thanks, Done

2017-05-30 03:19 UTC, Tuanlase02874 commented
Thanks Vinh and hieulq for review my commit

2017-05-30 03:54 UTC, tovin07 commented on _posts/2017-05-29-high-availability-of-bare-metal.md
> +`$ git clone https://git.openstack.org/openstack-dev/devstack.git devstack`
không phải rồi

Chú làm thế này này.
Chỉ việc:
1. Copy
2. Xóa dấu cách ở đầu mỗi dòng đi :man_facepalming: 

````
 ```bash
 $ git clone https://git.openstack.org/openstack-dev/devstack.git devstack
 $ sudo ./devstack/tools/create-stack-user.sh
  ```
````

2017-05-30 03:55 UTC, tovin07 commented on _posts/2017-05-29-high-availability-of-bare-metal.md
> +```
Chỗ này gần đúng rồi, thêm bash vào nhé

2017-05-30 03:55 UTC, tovin07 commented on _posts/2017-05-29-high-availability-of-bare-metal.md
> +`$ ironic node-validate bm`
Sửa như trên anh bảo

2017-05-30 03:55 UTC, tovin07 commented on _posts/2017-05-29-high-availability-of-bare-metal.md
> +```
đã thấy done đâu mà remove comment? thêm ini vào nữa đi chú

2017-05-30 03:56 UTC, tovin07 commented on _posts/2017-05-29-high-availability-of-bare-metal.md
> +This tutorial will show how to create bare metal computer (BM) with port groups support follow the network prototype here:
Chú vẫn không sửa theo comment của anh @hieulq sao đã remove comment rồi?

2017-05-30 03:56 UTC, tovin07 requested changes
Nhiều chỗ anh có thấy sửa gì đâu mà sao đã mark review là done?

2017-05-30 04:24 UTC, hieulq requested changes
boo :-1:

2017-05-30 04:33 UTC, hieulq commented
@vietstacker/organizer anh em vào review (chịu nhục) nhé

2017-05-30 06:50 UTC, tovin07 commented on _posts/2017-05-29-high-availability-of-bare-metal.md
> +```init
ini chứ không phải init nhé

2017-05-30 06:51 UTC, tovin07 commented on _posts/2017-05-29-high-availability-of-bare-metal.md
> +ironic node-update bm add driver_info/ipmi_username=$IRMC_USERNAME driver_info/ipmi_password=$IRMC_PASSWORD driver_info/ipmi_address=$IRMC_IP driver_info/irmc_username=$IRMC_USERNAME driver_info/irmc
có thể dung gạch ngược (backslask) để concat multi-lines được không? cho dễ đọc chú ơi!

2017-05-30 06:51 UTC, tovin07 commented on _posts/2017-05-29-high-availability-of-bare-metal.md
> +$ ironic node-update bm add properties/memory_mb='32768' properties/cpu_arch='x86_64' properties/local_gb=$MEMMORY properties/cpus='8'
như trên

2017-05-30 06:52 UTC, tovin07 requested changes
một số nits

2017-05-30 07:18 UTC, hieulq commented
@Tuanlase02874 commit message có nghĩa tí đi em, toàn add với improve format thế.
Lần này thì accept, lần sau close luôn nhé

2017-05-31 01:14 UTC, hieulq approved these changes
Tạm thời approve để đỡ phải chịu nhục.

2017-05-31 01:14 UTC, tovin07 approved these changes

2017-05-31 01:15 UTC, merged