Update Rolling upgrade part 2
vietstacker/vietstacker.github.io pull request #37
Opened 2017-06-05 03:01 UTC by NguyenHoaiNam

2017-06-05 03:05 UTC, hieulq requested changes

2017-06-05 03:05 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +layout: post
^M --> ?

2017-06-05 03:05 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Thân ái, hẹn gặp lại!
cho thêm cái chữ ký và tên tuổi đi nào

2017-06-05 03:05 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +  email: namnh@vn.fujitsu.com
dùng mail cá nhân đi

2017-06-05 03:17 UTC, hieulq commented
@NguyenHoaiNam anh thay mặt anh @congto xin gửi lời cám ơn em đã đóng góp cho cộng đồng, mọi vấn đề về kỹ thuật anh em trong BQT sẽ thay anh @congto xử lý. :1st_place_medal:

2017-06-05 03:18 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +layout: post
Chắc là do em copy paste ở notepad++

2017-06-05 03:18 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +  email: namnh@vn.fujitsu.com
Vâng anh

2017-06-05 03:18 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Thân ái, hẹn gặp lại!
Ok anh

2017-06-05 03:18 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Thân ái, hẹn gặp lại!
Còn thêm gì nữa không anh

2017-06-05 03:19 UTC, hieulq requested changes
chớt chát!

2017-06-05 03:19 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Thân ái, hẹn gặp lại!
đã sửa xong đâu mà thêm hay không thêm.

2017-06-05 03:19 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +  email: namnh@vn.fujitsu.com
vẫn chưa remove

2017-06-05 03:24 UTC, ducnc commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Thân ái, hẹn gặp lại!
> tám tính tính trong Rolling upgrade

 Chỗ này ý là sao nhỉ?

2017-06-05 03:34 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- Bài dịch - Tài liệu
Các cái categories này mình để tự do hay là có rules nào không @hieulq nhỉ?

2017-06-05 03:35 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Trong seri tiếp theo của chủ đề **Rolling upgrade** tôi sẽ phân tích về tám tính năng mà một project cần được hỗ trợ để được công nhận có tính năng Rolling upgrade.
seri thì dịch xừ thành phần đi

2017-06-05 03:38 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Cho phép thay đổi lược đồ cơ sở dữ liệu mà **không** yêu cầu tắt hết dịch vụ (không hỗ trợ thay đổi về phiên bản cũ hơn).
*tắt: hay là khởi động lại?
Cả đoạn viết về cái này anh nghĩ chú nên viết lại, viết thế này tối + trẻ trâu lắm.

2017-06-05 03:39 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Lời giải chính là việc tôi sẽ phân tích từng giai đoạn để các bạn có thể thấy được không có thời điểm nào, mà service xung đột với database
vậy lời giải là gì?

2017-06-05 03:40 UTC, hieulq requested changes

2017-06-05 03:40 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- Bài dịch - Tài liệu
cái này do sếp @congto tự sướng và fill tùm lum, anh chịu

2017-06-05 03:41 UTC, hieulq commented
@vietstacker/owners anh em nên start review và add comment 1 loạt, cuối cùng thì publish review thì nó sẽ tổng hợp thành 1 flow comment/review luôn, đừng add single comment, mail bắn tùm lum sợ lắm

2017-06-05 03:41 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Khi 2 services (A và B) đang chạy tại phiên bản N thì chúng đều tương tác với “old” table.
Không dùng dấu nháy  ``“`` này nhá, chú viết trên word đúng không :))

2017-06-05 03:42 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Nhờ có tính năng rolling upgrade mà tao không phải upgrade 2 service cùng một thời điểm mà ta có thể làm lần lượt:
*tao?

2017-06-05 03:43 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Chúng ta đã hoàn thành quá trình upgrade hệ thống sử dụng trigger để xử lý vấn đề thay đổi database. Các bạn cũng thấy rằng trong suốt quá trình rolling upgrade thì service ở phiên bản cũ hay phiên b
lúc thì database lúc thì DB

2017-06-05 03:47 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Tiếp theo tôi sẽ phân tích tính năng thứ hai là
câu cú kiểu gì thế này :))

2017-06-05 03:49 UTC, hieulq commented
@NguyenHoaiNam thân tặng chú khóa này http://hanoistar.edu.vn/content/mot-so-bien-phap-khac-phuc-loi-chinh-ta-o-lop-3

2017-06-05 03:56 UTC, tovin07 requested changes
Thôi, tạm thế đã, nhiều kín chỗ review rồi :v:

2017-06-05 03:56 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Vậy câu chuyện là khi người vận hành muốn bảo trình một node nova-compute 30 thì đâu tiên họ phải ra lệnh cho nova kích hoạt chế độ **maintenance mode** cho node nova-compute 30 lên, lúc đó nova-sche
*bảo trình
*đâu tiên

2017-06-05 03:56 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +=> Đó chính là ý nghĩa của tính năng **Maintenance Mode**.
Không dùng ``=>`` nhé thanh niên, trình bày kiểu khác đi

2017-06-05 03:56 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Trong bài tiếp theo, chúng ta sẽ tiếp tục phân tích về các tính chất còn lại của tám tính tính trong Rolling upgrade.
Thêm tham khảo vào nhé, lỡ người ta quên mất và chẳng biết xem 8 tính chất ấy ở đâu.

2017-06-05 03:56 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Vậy **“trigger”** là gì: Trigger được hiểu đơn giản là một thủ tục được thực thi trong database khi có một sự kiện xảy ra như update, insert hay delete.
Những từ khóa kiểu như trigger mà chú muốn làm nổi lên thi cho nó vào trong mấy cái backtick để nó hiện lên như thế này có khi sẽ dễ quan sát hơn.
VD: `trigger`

2017-06-05 03:56 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +**Bài toán:** Database của một service tại phiên bản N có một bảng tên là “old” nhưng sang database tại phiên bản N+1 đã bị xóa và thay thế bằng bảng mới tên là “new”. Vậy làm thế nào để người dùng s
Tô đậm bài toán kiểu khác đi, chứ thế này nó lẫn vào nền bài viết chú ạ

2017-06-05 03:56 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +![image2](../pictures/rolling_upgrade_part_2.png)
Dẫn nguồn cho kiến thức kiểu này nhé

2017-06-05 03:56 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Hãy thử hình dung rằng có 2 services (A và B) cùng tương tác với database:
`2 services` hay `2 service` anh thấy chú dùng không thống nhất ở các chỗ khác nhau

2017-06-05 03:56 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- Contract: dùng xóa cột, bảng, trigger trong database.
thêm chữ `để` vào nữa cho đẹp trai ;v

2017-06-05 04:40 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Cho phép thay đổi lược đồ cơ sở dữ liệu mà **không** yêu cầu tắt hết dịch vụ (không hỗ trợ thay đổi về phiên bản cũ hơn).
Tắt anh ạ,
Đoạn này em lấy từ phần một sang

2017-06-05 04:41 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Lời giải chính là việc tôi sẽ phân tích từng giai đoạn để các bạn có thể thấy được không có thời điểm nào, mà service xung đột với database
em nghĩ em nên sửa thành thế này: "lời giải là việc sử dụng trigger và tôi sẽ phân tích từng giai đoạn để các bạn có thể thấy được không có thời điểm nào, mà service xung đột với database"

2017-06-05 04:41 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Lời giải chính là việc tôi sẽ phân tích từng giai đoạn để các bạn có thể thấy được không có thời điểm nào, mà service xung đột với database
a thấy thế nào

2017-06-05 04:42 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Khi 2 services (A và B) đang chạy tại phiên bản N thì chúng đều tương tác với “old” table.
=)) Em viết trên notepadd++

2017-06-05 04:43 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Nhờ có tính năng rolling upgrade mà tao không phải upgrade 2 service cùng một thời điểm mà ta có thể làm lần lượt:
=)))

2017-06-05 06:29 UTC, congto commented
@NguyenHoaiNam @hieulq làm đê, nói ít thôi. Merge nhanh còn show

2017-06-05 06:35 UTC, hieulq commented
@NguyenHoaiNam ko đẩy commit đi, sếp @congto  nói rồi kìa

2017-06-05 07:00 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Lời giải chính là việc tôi sẽ phân tích từng giai đoạn để các bạn có thể thấy được không có thời điểm nào, mà service xung đột với database
Anh cũng không chắc lắm, vì anh cũng không thực sự hiểu rõ chủ đề này mà. Đại ý là viết câu ấy cho nó thoát ý vào.
Theo cách chú viết lại, lời giải lúc này `là việc sử dụng trigger`, chỉ có trigger thôi à, hay là còn cách khác nữa vì anh còn hóng thấy cả triggerless/trigger-based gì đó nữa mà.

2017-06-05 07:00 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- Bài dịch - Tài liệu
Vâng, thế thì em đã tạm hiểu :v

2017-06-05 07:00 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Cho phép thay đổi lược đồ cơ sở dữ liệu mà **không** yêu cầu tắt hết dịch vụ (không hỗ trợ thay đổi về phiên bản cũ hơn).
Okay

2017-06-05 15:37 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Trong bài tiếp theo, chúng ta sẽ tiếp tục phân tích về các tính chất còn lại của tám tính tính trong Rolling upgrade.
Căng ghê, nãy em vừa xem lại nguồn của 8 tính chất này, nó đã update lại thành 10 phần luôn rồi anh (cơ bản là nó chia nhỏ ra)

2017-06-05 15:39 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +=> Đó chính là ý nghĩa của tính năng **Maintenance Mode**.
Vâng anh, thế em xóa kí tự đó đi.

2017-06-05 15:46 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +![image2](../pictures/rolling_upgrade_part_2.png)
Để mai lênh công ty em xem slide đó tên là gì anh nhé, bây giờ em ứ nhớ link nữa, tại e tải luôn cái slide đó về máy =))

2017-06-05 15:47 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- Contract: dùng xóa cột, bảng, trigger trong database.
Nhất trí anh.

2017-06-05 15:47 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +**Bài toán:** Database của một service tại phiên bản N có một bảng tên là “old” nhưng sang database tại phiên bản N+1 đã bị xóa và thay thế bằng bảng mới tên là “new”. Vậy làm thế nào để người dùng s
Anh có suggest gì không ạ?

2017-06-05 15:48 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Vậy **“trigger”** là gì: Trigger được hiểu đơn giản là một thủ tục được thực thi trong database khi có một sự kiện xảy ra như update, insert hay delete.
Nhất trí, em sẽ ra lại từ khóa này.

2017-06-05 15:48 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Chúng ta đã hoàn thành quá trình upgrade hệ thống sử dụng trigger để xử lý vấn đề thay đổi database. Các bạn cũng thấy rằng trong suốt quá trình rolling upgrade thì service ở phiên bản cũ hay phiên b
thống nhất là database hết a nhé

2017-06-05 15:49 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Tiếp theo tôi sẽ phân tích tính năng thứ hai là
Trẻ trâu ạ, em sẽ sửa đổi

2017-06-05 15:49 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Vậy câu chuyện là khi người vận hành muốn bảo trình một node nova-compute 30 thì đâu tiên họ phải ra lệnh cho nova kích hoạt chế độ **maintenance mode** cho node nova-compute 30 lên, lúc đó nova-sche
Thanks for your review deeply

2017-06-06 01:43 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +![image2](../pictures/rolling_upgrade_part_2.png)
Phần này chỉ có một cái mailing-list của openstack glance và nó đính kèm thêm bản PDF của hình này thôi anh ạ

2017-06-06 03:31 UTC, hieulq requested changes
Ngữ pháp 1 điểm, về chỗ!

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Trong phần tiếp theo của chủ đề **Rolling upgrade** tôi sẽ phân tích về tám tính năng [1] mà một project cần được hỗ trợ để được công nhận có tính năng Rolling upgrade.
Cố gắng viết tổng quan, đừng dedicate rolling-upgrade cho OpenStack.
Ví dụ đoạn ở trên viết thành `tám tính năng [1] mà một project bất kỳ cần được`

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
Ngoài openstack ra thì còn thằng nào khác? Ví dụ FB cũng có nhé.

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +*Ví dụ*: ta có thể tạo ra một trigger để trước khi ghi một bản ghi vào trong table A thì tạo một bản ghi vào trong table B.
Tối nghĩa, lấy ví dụ khác đi, ví dụ `ta có thể tạo ra một trigger để thực hiện việc trước khi ghi một bản ghi vào trong table A thì update bản ghi có foreign-key tương ứng từ table B sang một giá trị khác`

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Vậy `trigger` là gì: Trigger được hiểu đơn giản là một thủ tục được thực thi trong database khi có một sự kiện xảy ra như update, insert hay delete.
được `thực thi một cách tự động`

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Sử dụng trigger và một trong những lời giải cho bài toán này và tôi sẽ phân tích từng giai đoạn để các bạn có thể thấy được không có thời điểm nào có service xung đột với database.
`Sử dụng trigger và một trong những` là sao?

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Lúc này database sẽ có "new" table và trigger. Nếu trên A và B tạo ra các bản ghi ở "old" table thì trigger sẽ làm nhiệm vụ copy nội dung cần thiết của bản ghi đó sang "new" table.
không phải là `copy nội dung` mà là thay đổi các record từ old table sang phù hợp với new table, copy thì nói làm gì nữa

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Copy toàn bộ dữ liệu ở "old" table trước thời điểm tạo trigger sang "new" table. Nghĩa là tất cả các hình ngũ giác màu xanh da trời sẽ được copy sang thành hình tam giác tương ứng tại "new" table.
Ditto

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Sau khi đã upgrade toàn bộ serivce lên (N+1) thì "old" table sẽ không được đọc ghi bởi bất kì service nào nữa, tất cả đã chuyển sang đọc ghi "new" table
typo: `serivce`

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
Ngoài hướng tiếp cận là `trigger` thì tại sao không viết luôn `triggerless` (ví dụ Github Gh-ost hay OpenStack Nova)

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Là chế độ đặt một node vào trạng thái duy trì, bảo hành sửa chữa để cho hệ thống không đặt resources trên node đó nữa khi có yêu cầu từ người dùng tạo mới resources. Tôi sẽ lấy một ví dụ cụ thể để mà
- Không phải là đặt một `node` mà là `service`
- `Tôi sẽ lấy một ví dụ cụ thể để mà một project đã tích hợp tính năng này vào đó chính là Nova.` --> Câu tối nghĩa, văn 1 điểm, về chỗ!

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Đó chính là ý nghĩa của tính năng **Maintenance Mode**.
`Để người vận hành có thể thao tác thoải mái với node nova-compute 30.` --> chủ ngữ, vị ngữ của câu này đâu?

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
Các tính chất còn lại là tính chất nào, list ra.

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
Ghi vào đây là `Vietnam OpenStack Community Organizer`. Đời có bao nhiêu thằng Nguyễn Hoài Nam?

2017-06-06 03:31 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Trong phần tiếp theo của chủ đề **Rolling upgrade** tôi sẽ phân tích về tám tính năng [1] mà một project cần được hỗ trợ để được công nhận có tính năng Rolling upgrade.
Ngoài ra thì nên liệt kê lại tám tính năng đó ở đây đi.

2017-06-08 07:34 UTC, tovin07 requested changes
Sửa nốt mấy cái nhỏ nhỏ nữa @NguyenHoaiNam nhé, có mấy cái nhỏ hơn thì thôi, anh không comment ở đây nữa, không ảnh hưởng lắm.

2017-06-08 07:34 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
khả năng bỏ được dòng trống này đấy

2017-06-08 07:34 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +2
số 2 này có ý nghĩa gì thế

2017-06-08 07:34 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +[2] https://github.com/github/gh-ost/blob/master/doc/why-triggerless.md
Cách thêm 1 dòng trống đi chú, không nó bị díu 2 dòng thành 1 dòng

2017-06-08 07:34 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- Pha (5) Contract phase
bỏ phase

2017-06-08 07:34 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- Pha (4) Deploy phase
bỏ phase

2017-06-08 07:34 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- Pha (3) Migrate database
sao chỗ này không thấy có dấu hai chấm như pha 2

2017-06-08 07:34 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Hình ngũ giác màu da cam thể hiện các dữ liệu được tạo ra tại pha expand, và hình tam giác màu da cam thể hiện các dữ liệu được tạo bởi trigger.
chú xem những chỗ trigger nào là những chỗ cần đặt trong thẻ code nhé

2017-06-08 07:34 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Vậy câu chuyện là khi người vận hành muốn bảo trì một node nova-compute 30 thì đầu tiên họ phải ra lệnh cho nova kích hoạt chế độ **maintenance mode** cho node nova-compute 30 lên, lúc đó nova-schedu
*t ạomáy

2017-06-08 07:34 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Lúc này database sẽ có "new" table và trigger. Nếu trên A và B tạo ra các bản ghi ở "old" table thì trigger sẽ làm nhiệm vụ thay đổi nội dung của bản gh iđó cho phù hợp với "new" table.
*gh iđó

2017-06-08 07:34 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Chúng ta đã hoàn thành quá trình upgrade hệ thống sử dụng trigger để xử lý vấn đề thay đổi database. Trong toàn bộ quá trình, service tại phiên bản N hay (N+1) cũng đều có thể tương tác với database,
triggerless thì gọi là không dùng trigger đi, làm màu quá đấy :))

2017-06-08 07:48 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Hình ngũ giác màu da cam thể hiện các dữ liệu được tạo ra tại pha expand, và hình tam giác màu da cam thể hiện các dữ liệu được tạo bởi trigger.
Vâng anh

2017-06-08 07:49 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
ok anh

2017-06-08 07:49 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Lúc này database sẽ có "new" table và trigger. Nếu trên A và B tạo ra các bản ghi ở "old" table thì trigger sẽ làm nhiệm vụ thay đổi nội dung của bản gh iđó cho phù hợp với "new" table.
Mịa mấy cái kiểu này, em viết bằng pycharm như nhiên nó cứ bị như thế, em sửa rồi mà vẫn sót.

2017-06-13 02:07 UTC, hieulq requested changes
@NguyenHoaiNam một số comment của anh từ các commit trước chưa xử lý xong.

2017-06-13 02:20 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Trong phần tiếp theo của chủ đề **Rolling upgrade** tôi sẽ phân tích về tám tính năng [1] mà một project cần được hỗ trợ để được công nhận có tính năng Rolling upgrade.
chưa fix

2017-06-13 02:21 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
FB có thì reference đâu?

2017-06-13 02:21 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
thiếu reference của FB

2017-06-13 02:23 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
chưa fix

2017-06-13 02:25 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
triggerless approach?

2017-06-13 02:25 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Đó chính là ý nghĩa của tính năng **Maintenance Mode**.
`Để người vận hành có thể thực hiện bảo trì với node nova-compute 30.` --> không hiểu ngữ cảnh câu này, ko chủ ngữ vị ngữ, không liên quan tới câu trước

2017-06-13 02:25 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Đó chính là ý nghĩa của tính năng **Maintenance Mode**.
chưa fix

2017-06-13 02:26 UTC, hieulq requested changes
Làm lại

2017-06-13 02:31 UTC, tovin07 commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
Thực ra, nếu chú viết thế này thì người đọc sẽ không thấy được cái tổng quan ngay ban đầu.
Nếu nhìn trên góc độ trigger, thì có hai loại trigger-based và trigger-less.
Sau khi nói dông dài về trigger (mà thực ra là nói về trigger-based) rồi chú mới văng cho 1 câu là có cả trigger-less.

2017-06-13 02:34 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Đó chính là ý nghĩa của tính năng **Maintenance Mode**.
Cá nhân em đọc đoạn này cũng hiểu,  với lại em học dốt tiếng việt lắm anh, em không hiểu chủ ngữ vị ngữ là gì đâu anh ơi =))) Cho em xin cái ví dụ với.

2017-06-13 02:35 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
Viết thêm cả cái này nữa ạ, em cho thêm theo comment trước của anh chứ không viết lan man sang triggerless

2017-06-13 02:35 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
Để em tìm phát =)))

2017-06-13 02:38 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +Đó chính là ý nghĩa của tính năng **Maintenance Mode**.
@NguyenHoaiNam sau khi dẫn dắt loằng ngoằng ở trên, em chốt cho 1 câu `Để abc xyz`. Anh đọc thì sẽ hiểu là `Để abcxyz thì ta cần...` mà hoàn toàn ko thấy đoạn sau ở đâu.
Đây chỉ là cách hành văn cơ bản. Tại sao ko sửa thành 
`Vậy câu chuyện là khi người vận hành muốn bảo trì một node nova-compute 30 thì đầu tiên họ phải ra lệnh cho nova kích hoạt chế độ **maintenance mode** cho node nova-compute 30 lên, lúc đó nova-scheduler sẽ không đặt việc tạo máy ảo trên node nova-compute 30 nữa kể cả tài nguyên trên node đó vẫn còn rất nhiều, khi có yêu cầu từ người dùng tạo máy ảo để người vận hành có thể thực hiện bảo trì với node nova-compute 30.`

2017-06-13 02:57 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
phải viết thì mới cover hết được

2017-06-28 04:03 UTC, hieulq commented
@NguyenHoaiNam ping?

2017-06-29 06:26 UTC, hieulq commented
@NguyenHoaiNam reopen when you have time

2017-06-29 08:40 UTC, NguyenHoaiNam commented
Sorry, I am so busy on this week for personal things.

2017-06-29 08:40 UTC, NguyenHoaiNam commented
Surely, I will reopen on next week

2017-07-16 09:46 UTC, hieulq commented
@NguyenHoaiNam next week = 17 days ago, right?

2017-08-01 01:05 UTC, hieulq requested changes
Sửa!

2017-08-01 01:05 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- *Rule 2:* Được phép xóa cột bảng của phiên bản N tại phiên bản N+1. Ví dụ như bảng A tại phiên bản N sẽ không được sử dụng tại phiên bản N+1 nhưng tại N+1 thì không được xóa bảng A mà phải chờ lên
`Được phép xóa cột bảng của phiên bản N tại phiên bản N+1` ?

2017-08-01 01:05 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- *Rule 1:* Chỉ được thêm và không được xóa sửa cột hoặc bảng tại hai phiên bản kế tiếp (từ N lên N+1) và những cột/bảng đó default là None để xử lý trường hợp service cũ ghi vào database nhưng không
typo `dữ liêu là None`

2017-08-01 01:05 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
Ưu nhược điểm và so sánh hai lời giải này thế nào? Người đọc thấy có 2 cách vậy thì nên chọn cách nào, phải phân tích ra chứ?

2017-08-01 01:17 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- *Rule 1:* Chỉ được thêm và không được xóa sửa cột hoặc bảng tại hai phiên bản kế tiếp (từ N lên N+1) và những cột/bảng đó default là None để xử lý trường hợp service cũ ghi vào database nhưng không
cái này là Null anh nhỉ?

2017-08-01 01:17 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- *Rule 2:* Được phép xóa cột bảng của phiên bản N tại phiên bản N+1. Ví dụ như bảng A tại phiên bản N sẽ không được sử dụng tại phiên bản N+1 nhưng tại N+1 thì không được xóa bảng A mà phải chờ lên
Ok để em update.

2017-08-01 01:18 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
Em cố tình không thêm đấy :)

2017-08-01 01:21 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- *Rule 1:* Chỉ được thêm và không được xóa sửa cột hoặc bảng tại hai phiên bản kế tiếp (từ N lên N+1) và những cột/bảng đó default là None để xử lý trường hợp service cũ ghi vào database nhưng không
liêu --> liệu

2017-08-01 01:22 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +
Tại sao lại ko viết?

2017-08-01 02:16 UTC, hieulq requested changes
Sửa tiếp!

2017-08-01 02:16 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +- Đối với trigger-lest:
lest?

2017-08-01 02:16 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +		- Dễ dàng cho việc implement.
Thế có dễ test không?

2017-08-01 02:20 UTC, NguyenHoaiNam commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +		- Dễ dàng cho việc implement.
Còn ý nào nữa không a nhỉ, em bổ sung nội. Hiện tại em nghĩ có mấy ưu nhược điểm đó.

2017-08-01 02:27 UTC, hieulq commented on _posts/2017-06-05-rolling-upgrade-part-2.md
> +		- Dễ dàng cho việc implement.
làm rolling-upgrade rồi mà không tự nghĩ tự tổng hợp lại được à còn hỏi anh? thích bị ban, kick và abandon không?

2017-08-01 03:34 UTC, hieulq approved these changes

2017-08-01 03:35 UTC, merged