OpenStack Ceph VM Crash on Power Loss
vietstacker/vietstacker.github.io pull request #42
Opened 2019-09-07 13:08 UTC by daikk115

2019-09-07 14:03 UTC, greatbn commented
LGTM

2019-09-07 17:07 UTC, tovin07 requested changes
Tổng quan thì khá ổn rồi đó.

Bên lề, góp ý thêm là có thể viết markdown theo kiểu `PEP8`, vừa là để dễ đọc khi review, vừa là để trình bày đẹp và cẩn thận.

Theo dõi thêm các rule khi viết markdown với markdownlint: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md

2019-09-07 17:07 UTC, tovin07 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +![Pray for server](pray_for_server.jpg)
Dẫn nguồn ảnh nhé thanh niên

2019-09-07 17:07 UTC, tovin07 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +- Reset compute node, máy ảo bị crash, kể cả hard boot cũng không giải quyết được --> Lúc này lock của image vẫn y chang như cũ
`hard boot` --> `hard reboot` ?

2019-09-07 17:07 UTC, tovin07 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +```
thêm `bash` hoặc `shell` để có syntax highlighting

2019-09-07 17:07 UTC, tovin07 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +```
ditto

2019-09-07 17:07 UTC, tovin07 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +- Trước và sau khi hardreboot
`hardreboot` viết liền hay cách thế?

2019-09-07 17:07 UTC, tovin07 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +```
ditto

2019-09-07 17:07 UTC, tovin07 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +```
ditto

2019-09-07 17:07 UTC, tovin07 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +Ngoài ra, lock của các Ceph image (hay OpenStack volume) cũng thay đổi mỗi khi soft/harde reboot máy ảo OpenStack
tito `harde`

2019-09-07 17:07 UTC, tovin07 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +- Thực hiện remove lock và hard reboot --> Máy ảo hoạt động trở lại bình thường
lịch sự đúng chuẩn người Viettel thì nên có dấu chấm câu, tự check cả các chỗ khác nữa đi :))

2019-09-07 17:07 UTC, tovin07 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +Quả thực, lúc đầu tôi nghĩ là do cache của rbd trên compute node vì nghĩ compute node tắt đột ngột quá là file system bị lỗi chăng. Nhưng lỗi kiểu này thì bình thường `fsck` là xong ấy thế mà lại khô
thừa space ở đây này `để  fix`

2019-09-07 17:15 UTC, daikk115 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +- Reset compute node, máy ảo bị crash, kể cả hard boot cũng không giải quyết được --> Lúc này lock của image vẫn y chang như cũ
tito ạ.

2019-09-07 17:18 UTC, daikk115 commented on _posts/2019-09-07-openstack-virtual-machine-on-ceph-crash-after-power-loss-part-1.md
> +- Thực hiện remove lock và hard reboot --> Máy ảo hoạt động trở lại bình thường
Haha, vâng ạ.

2019-09-07 17:21 UTC, daikk115 commented
> Tổng quan thì khá ổn rồi đó.
> 
> Bên lề, góp ý thêm là có thể viết markdown theo kiểu `PEP8`, vừa là để dễ đọc khi review, vừa là để trình bày đẹp và cẩn thận.
> 
> Theo dõi thêm các rule khi viết markdown với markdownlint: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md

Thank anh, em vừa update lại ạ

2019-09-08 01:38 UTC, tovin07 approved these changes

2019-09-08 01:38 UTC, merged